# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
########################################
  - name: Posts
    url: 'post'
    weight: 20
    identifier: 'postsubmenu'
  - name: News and Events
    url: 'post/news'
    weight: 10
    parent: 'postsubmenu'
  - name: Security
    url: 'post/security'
    weight: 20
    parent: 'postsubmenu'
  - name: Development
    url: 'post/development'
    weight: 30
    parent: 'postsubmenu'
  - name: Network
    url: 'post/network'
    weight: 40
    parent: 'postsubmenu'
  - name: Server
    url: 'post/server'
    weight: 50
    parent: 'postsubmenu'
  - name: Poem
    url: 'post/poem'
    weight: 60
    parent: 'postsubmenu'
########################################
  - name: Academic
    url: 'academic'
    weight: 30
    identifier: 'academicsubmenu'
  - name: Research
    url: 'academic/research'
    weight: 10
    parent: 'academicsubmenu'
  - name: Teaching
    url: 'academic/teaching'
    weight: 30
    parent: 'academicsubmenu'
  - name: Patent
    url: 'academic/patent'
    weight: 30
    parent: 'academicsubmenu'
########################################
  - name: Projects
    url: 'project'
    weight: 40
########################################
  - name: Publication
    url: 'publication'
    weight: 50
    identifier: 'publicationsubmenu'
########################################
  - name: Resumé/CV
    url: 'uploads/repozitorCV.pdf'
    weight: 60
    identifier: 'allresume'
  - name: Javad Zandi
    url: 'uploads/repozitorCV.pdf'
    weight: 10
    parent: 'allresume'
  - name: Maryam Hatami
    url: 'uploads/hatami.pdf'
    weight: 20
    parent: 'allresume'
########################################
  - name: Contact
    url: 'contact'
    weight: 70