name: github pages

on:
  push:
    branches: [ master ] # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Clean public directory
        run: rm -rf public

      - name: Build
        run: hugo --minify

      #- name: Create cname file
      #  run: echo 'repozitor.com' > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.810e6406f944d1bfdd0ee7dde013b23b06ca68cc }}
          publish_dir: ./public
          #allow_empty_commit: true